#jre环境
FROM openjdk:11-jdk

#维护者信息
MAINTAINER smithwang

#设置环境变量-运行时也可传参数""
ENV JAVA_OPTIONS ""

#添加Jar包到容器中 --tips xx.jar 和DockerFile 在同一级
ADD *.jar /home/app.jar

#对外暴露的端口
#[注:EXPOSE指令只是声明容器运行时提供的服务端口，给读者看看有那些端口，在运行时只会开启程序自身的端口！！]
EXPOSE 8333

#以EXEC格式的CMD指令--可实现优雅停止容器服务
#“sh” “-c” : 可以通过exec模式执行shell =》环境变量
CMD ["sh","-c","echo \"**** 运行命令:java -jar ${JAVA_OPTIONS} /home/app.jar\" & java -jar ${JAVA_OPTIONS} /home/app.jar"]